Update tooling for OCP 4.17; update base images
redhat-developer/web-terminal-tooling pull request #73
Opened 2024-10-10 01:22 UTC by AObuchow

This PR updates the tooling used in the web terminal operator tooling container to their latest versions available on mirror.openshift.com and github releases for OCP 4.17, as well as updates the base container images to their latest available versions.

# Testing
For convenience, I've pushed the web terminal tooling container built from this PR to `quay.io/aobuchow/wto-tooling:1.12`.

1. On a cluster with Web Terminal installed, create a web terminal, click the link to specify a custom image, and provide `quay.io/aobuchow/wto-tooling:1.12`. Alternatively, create a web terminal with the default image and run `wtoctl set image quay.io/aobuchow/wto-tooling:1.12` in the web terminal console
2. Verify the web terminal starts up successfully. The provided binaries should be updated to the versions specified in this PR. For example, running `oc version` should indicate version 4.17.

Here's the output of `help` from the tooling image, running on the Developer Sandbox:
![image](https://github.com/user-attachments/assets/6e6d7e18-8e6d-4eb0-b08a-959bff9f36ac)

2024-10-11 15:16 UTC, dkwon17 requested changes

2024-10-11 15:16 UTC, dkwon17 commented on README.md
> +- [oc](https://github.com/openshift/origin) [v4.17.0](https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/4.17.0)
@AObuchow I just noticed that the `mirror.openshift.com` links need a trailing forward slash or else we get a 404 error. Could you update it?

2024-10-15 15:57 UTC, AObuchow commented on README.md
> +- [oc](https://github.com/openshift/origin) [v4.17.0](https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/4.17.0)
Good catch @dkwon17 :) I've updated all the links with required slashes and verified that they now all work.

2024-10-15 20:41 UTC, dkwon17 approved these changes

2024-10-15 20:43 UTC, merged